### ISSUE TITLE
Docker compose based self-hosting

### ISSUE THREAD

**Issue by accforgithubtest** [davidguva/OpenVidReview#1]
This is something I really would like to self-host.
A docker compose based set-up would be ideal for self-hosters.

1. A pre-built docker image available on dockerhub, ghcr, etc.
2. A clear example on the readme showing how to selfhost using compose (env variables, ports, volumes, etc)

**Comment by davidguva** [comment]
Awesome! Added to the main-branch.

**Comment by accforgithubtest** [comment]
Thanks @guerrieroriccardo and @davidguva !
Are you considering publishing a docker image to docker hub / ghcr ? This would be useful so users do not have to checkout the code and build the image themselves, instead use a image based on the projects official release versions / tags.
